---
apiVersion: v1
kind: Template
metadata:
  name: python-crash-me-template-build
  annotations:
    description: Build application template.
labels:
  name: python-crash-me-template
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/name: ${APP_NAME}
    name: ${APP_NAME}
    namespace: "${NAMESPACE}"
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${IMAGE_NAME}:latest
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/themoosman/ocp-python-crash-me.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ${BASE_IS_NAME}
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5

parameters:
  - name: GIT_URI
    description: The Git URI.
    value: "https://github.com/themoosman/ocp-python-crash-me.git"
    required: true
  - name: GIT_REF
    description: The Git branch.
    value: "master"
  - name: IMAGE_NAME
    description: The name of the image.
    value: py-crash-me
    required: true
  - name: IMAGE_VERSION
    description: The version of the images to use.
    value: "latest"
  - name: NAMESPACE
    description: Target namespace for the application.
    required: true
  - name: APP_NAME
    description: Application name.
    value: py-crash-me
    required: true
  - name: BASE_IS_NAME
    description: Name of the application base imaagestream.
    value: "python:3.8-ubi8"
    required: true