---
apiVersion: v1
kind: Template
metadata:
  name: python-crash-me-template-dev
  annotations:
    description: Dev application template.
labels:
  name: python-crash-me-template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/name: ${APP_NAME}
    name: ${APP_NAME}
    namespace: "${NAMESPACE}"
  spec:
    lookupPolicy:
      local: false
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/name: ${APP_NAME}
    name: ${APP_NAME}
    namespace: "${NAMESPACE}"
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - image: ${IMAGE_NAME}
          imagePullPolicy: Always
          env:
          - name: DEPLOY_ENV
            value: ${ENVIRONMENT}
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/status.up
            failureThreshold: 1
            initialDelaySeconds: 45
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          name: ${APP_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 25
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: false
        containerNames:
        - ${IMAGE_NAME}
        from:
          kind: ImageStreamTag
          name: ${IMAGE_NAME}:${IMAGE_VERSION}
          namespace: ${NAMESPACE}
      
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/name: ${APP_NAME}
    name: ${APP_NAME}
    namespace: "${NAMESPACE}"
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/name: ${APP_NAME}
    name: ${APP_NAME}
    namespace: "${NAMESPACE}"
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    labels:
      template: ${APP_NAME}
    name: py-crash-edit
    namespace: ${NAMESPACE}
  groupNames: null
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: ServiceAccount
    name: ${SA_NAME}
    namespace: ${IMAGE_NAMESPACE}
  userNames:
  - system:serviceaccount:${IMAGE_NAMESPACE}:${SA_NAME}

parameters:
  - name: IMAGE_NAME
    description: The name of the image.
    value: py-crash-me
    required: true
  - name: IMAGE_VERSION
    description: The version of the images to use.
    value: "latest"
  - name: NAMESPACE
    description: Target namespace for the application.
    required: true
  - name: IMAGE_NAMESPACE
    description: Source namespace for the ImageStream
    required: true
  - name: APP_NAME
    description: Application name.
    value: py-crash-me
    required: true
  - description: Name of a service account that can deploy to this project
    name: SA_NAME
    required: true
    value: py-crash-sa
  - description: Test ENV Var
    name: ENVIRONMENT
    required: true