apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}app-high-cpu-usage
spec:
  groups:
  - name: {{ .Release.Name }}-high-cpu-usage
    rules:
    - alert: App High CPU Usage ({{ .Release.Name }})
      expr: sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster="", namespace="{{ .Release.Namespace }}"}) by (pod) > .80
