apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-high-cpu-usage
spec:
  groups:
  - name: app-high-cpu-usage
    rules:
    - alert: App High CPU Usage
      expr: sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster="", namespace="{{ .Release.Namespace }}"}) by (pod) > .80
