apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}
    deploymentconfig: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP